name: brain_dev_tools
description: "brain_dev_tools est un plugin tout-en-un conçu pour simplifier le développement Flutter en regroupant plusieurs utilitaires essentiels en un seul package. Il inclut des outils pour la gestion des dates, le stockage local, la manipulation de chaînes, les conversions de données et bien plus encore. Idéal pour les développeurs cherchant à optimiser leur code avec des fonctions réutilisables et performantes."
version: 1.0.1+1
homepage: https://github.com/Grafritz/brain_dev_tools_plugin.git

#  dart pub publish --dry-run   #// Vérifier avant chaque nouvelle version
#  dart pub login
#  dart pub publish            # Publier la mise à jour

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8


  app_links: ^6.4.0
  auto_size_text: ^3.0.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.2
  easy_image_viewer: ^1.5.1
  #external_app_launcher: ^4.0.1
  get: ^4.7.2
  google_fonts: ^6.2.1

  http: ^1.3.0 # A cause Plugin
  http_parser: ^4.1.2 # A cause Plugin

  #in_app_review: ^2.0.10
  in_app_update: ^4.2.3 #Only Android
  intl: ^0.19.0
  launch_app_store: ^1.1.2
  package_info_plus: ^8.3.0

  path: ^1.9.1 # A cause Plugin
  path_provider: ^2.1.5 # A cause Plugin

  pull_to_refresh: ^2.0.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  # Android, iOS, Web
  flutter_custom_tabs: ^2.1.0
  flutter_flavor: ^3.1.4
  flutter_smart_dialog: ^4.9.8+7
  flutter_speed_dial: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html_core: ^0.16.0
  #flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.8.0

  #  pdf_render: ^1.4.12

  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  showcaseview: ^4.0.1
  #sqflite: ^2.4.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: net.braindev.brain_dev_tools
        pluginClass: BrainDevToolsPlugin
      ios:
        pluginClass: BrainDevToolsPlugin
      linux:
        pluginClass: BrainDevToolsPlugin
      macos:
        pluginClass: BrainDevToolsPlugin
      windows:
        pluginClass: BrainDevToolsPluginCApi
      web:
        pluginClass: BrainDevToolsWeb
        fileName: brain_dev_tools_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/img/bg/
    - assets/img/flags/
    - assets/locale/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
